export { createImageIntake } from './promise-intake.js';
export { resolveOutputOptions, resolveTargetDimensions } from './options.js';
export type {
  DropTarget,
  DropTargetOptions,
  FallbackImageResult,
  ImageFallback,
  ImageFallbackRequest,
  ImageIntake,
  ImageIntakeError,
  ImageIntakeOptions,
  ImageOutputFormat,
  ImageOutputFormatOption,
  ImageOutputOptions,
  ImagePlan,
  ImageProgressEvent,
  ImageProgressHandler,
  ImageProgressStage,
  ImageResult,
  LocalExecution,
  LocalImageResult,
  NativeDecodeCapability,
  ProcessingExecution,
  ProcessImageOptions,
  ResolvedImageOutputOptions,
  RunImageOptions,
  TargetDimensions,
} from './types.js';

export {
  AnimationNotAllowedError,
  DecodeError,
  DimensionsUnknownError,
  EncodeError,
  EnvironmentUnsupportedError,
  FileEmptyError,
  FrameLimitExceededError,
  InputTooLargeError,
  InvalidDimensionsError,
  InspectionReadError,
  PixelLimitExceededError,
  ProcessingTimeoutError,
  ServerFallbackRequiredError,
  SourceDimensionExceededError,
  UnsupportedFormatError,
  checkImagePolicy,
  defaultImagePolicy,
  formatExtensions,
  formatMediaTypes,
  imageFormats,
  inspectImageBytes,
  isOptloadError,
  resolveImagePolicy,
  type BlobLike,
  type ExifOrientation,
  type FileLike,
  type ImageFormat,
  type ImageInspection,
  type ImagePolicy,
  type ImagePolicyDecision,
  type ImagePolicyError,
  type ImageProcessingError,
  type InspectImageOptions,
  type InspectionError,
  type InspectionWarning,
  type InspectionWarningCode,
  type OptloadError,
  type OptloadErrorCode,
  type OptloadStage,
  type PolicyIssue,
  type PolicyIssueCode,
  type ResolvedImagePolicy,
  type SupportedInputFormat,
  type UnknownDimensionBehavior,
} from '@optload/core';
